### ISSUE TITLE
Conduct meeting

### ISSUE THREAD

**Issue by CkayeValencia** [CkayeValencia/Et0eh-L4ng-Ak03h#1]
Can we meet later at 9:30 pm for further discussion about our final project?

**Comment by CkayeValencia** [comment]
Thank you for  your cooperation guys.

**Comment by Mervz22** [comment]
Alright, see you later. ehhehehe

**Comment by LapasaranMarkClarence** [comment]
Sige, available ako

**Comment by CkayeValencia** [comment]
**Everyone**, please from now on dito na tayo mag chat chat or and discuss about projects ha. Arigathankssss!!! SEE YOUUUU

**Comment by Kyle-Marie-Baita** [comment]
Pwede po bha na malate ako. I will have my dinner kasi

**Comment by CkayeValencia** [comment]
> Pwede po bha na malate ako. I will have my dinner kasi

Sure, basta if possible pakibilis hehehe para konti lang masayang na oras thanksss

**Comment by Kyle-Marie-Baita** [comment]
> > Pwede po bha na malate ako. I will have my dinner kasi
> 
> Sure, basta if possible pakibilis hehehe para konti lang masayang na oras thanksss

ok po thank you

**Comment by CkayeValencia** [comment]
As discuss, me and kyle will make the background design and we will be studying furthermore about github. For mervin, mark and kenneth kayo magplan for outcome saating stopwatch and sa mga dapat pa ilearn. Thank you for cooperating guys.!

**Comment by Kyle-Marie-Baita** [comment]
Thank you everyone. See you again next meeting

**Comment by Mervz22** [comment]
Got it!. Teeeeenks.

**Comment by LapasaranMarkClarence** [comment]
Thanks guys!! Kaya natin to! <3

**Comment by CkayeValencia** [comment]
![Capture](https://user-images.githubusercontent.com/105430197/169656620-aaba4225-f882-4b41-b3ed-8bcb68356658.JPG)
