### ISSUE TITLE
Upload necessary files

### ISSUE THREAD

**Issue by Mervz22** [CkayeValencia/Et0eh-L4ng-Ak03h#10]
Hello @LapasaranMarkClarence , @CkayeValencia, @Kyle-Marie-Baita,

Could you guys upload the necessary files required to run our code? I dont have them right now, but I think you three has them. Upload it on developer branch

**Comment by CkayeValencia** [comment]
> Hello @LapasaranMarkClarence , @CkayeValencia, @Kyle-Marie-Baita,
> 
> Could you guys upload the necessary files required to run our code? I dont have them right now, but I think you three has them. Upload it on developer branch

Done na po. I Uplaoded the lap and Reset button

**Comment by Kyle-Marie-Baita** [comment]
Done na po

**Comment by LapasaranMarkClarence** [comment]
Na upload ko na po. Sorry kung natagalan, nawalan kasi kami ng net

**Comment by CkayeValencia** [comment]
Can u upload this to the master branch? right away? thanks

**Comment by KennethJonesDSerrano** [comment]
I already upload the file that you need @CkayeValencia.

**Comment by LapasaranMarkClarence** [comment]
I also uploaded the Requirement.txt in the master branch.
