### ISSUE TITLE
File location error 

### ISSUE THREAD

**Issue by KennethJonesDSerrano** [CkayeValencia/Et0eh-L4ng-Ak03h#11]
naga error ang pag locate sa mga file paki fix nalagn @LapasaranMarkClarence

**Comment by LapasaranMarkClarence** [comment]
Tapos na, na edit ko na ang code

**Comment by Kyle-Marie-Baita** [comment]
may bug parin sa code natin

**Comment by Kyle-Marie-Baita** [comment]
naga error parin po siya

**Comment by KennethJonesDSerrano** [comment]
okay na ang lahat
