### ISSUE TITLE
Finalization of Code!

### ISSUE THREAD

**Issue by Kyle-Marie-Baita** [CkayeValencia/Et0eh-L4ng-Ak03h#12]
[meet.google.com/qio-wqyv-vzr](http://meet.google.com/qio-wqyv-vzr?fbclid=IwAR1y0TpK8mlgUhlEG_QdOXB5b1wm68YswCSwWKweY_sVivTkOdD-I9U7LF4)

**Comment by Kyle-Marie-Baita** [comment]
Pasok lang po kayu sa gmeet for finalization sa code

**Comment by Kyle-Marie-Baita** [comment]
kung may dagdag kayu sa code or may iiba kayo...pls inform nyo dito

**Comment by KennethJonesDSerrano** [comment]
okay2

**Comment by Kyle-Marie-Baita** [comment]
na post ko na po yung part ko

**Comment by LapasaranMarkClarence** [comment]
Na finalize ko na ang part ko sa code

**Comment by KennethJonesDSerrano** [comment]
so far okay na yong codes ko

**Comment by Mervz22** [comment]
Already finalized the code
