### ISSUE TITLE
The last discussion 

### ISSUE THREAD

**Issue by KennethJonesDSerrano** [CkayeValencia/Et0eh-L4ng-Ak03h#14]
Guys thankyou masyado sa lahat, ma miss ko mga late night talks natin. Sana kahit tapos na ang project natin kay wala parin mag bago. lagi nyong tandaan na lab na lab ko kayo. 🥹🥹🥹

**Comment by Mervz22** [comment]
Thank you and hakdog well :heart:  :3

**Comment by Kyle-Marie-Baita** [comment]
Thank you so much guys. Maraming salamat tagala sa time and effort na gi spend ng bawat isa para matapos tung final project. See you all soon guys.

**Comment by CkayeValencia** [comment]
Thank you sa tanan na mga effort guys! without you hindi tayo magkakaroon ng mga kalate night talks and sa proj ta hehehe labyu all

**Comment by LapasaranMarkClarence** [comment]
Thank you so much guys! I'm so blessed sinali niyo ako sa grupo. Dahil sa inyo may kasama ako gabi-gabi. Thank you sa late night talks. Mahal ko kayo! Chariz <3
