### ISSUE TITLE
Requesting for more co-DEV

### ISSUE THREAD

**Issue by Mervz22** [CkayeValencia/Et0eh-L4ng-Ak03h#2]
In developing a tkinter code, our co-developer, Mark, need more help from another co-developers with specialty on this specific tkinter subject, and fortunately, both of you Kyle and Kaye has the ability to help our co-developer, Mark. We are calling you, Kyle and Kaye to help us developing our code for this project. Kyle and Kaye, could you help Mark, and us co-developers on creating code for our current project and become one of us as another co-developers? Thank you.

**Comment by CkayeValencia** [comment]
Hello, goodmorning, I will gladly help.

> In developing a tkinter code, our co-developer, Mark, need more help from another co-developers with specialty on this specific tkinter subject, and fortunately, both of you Kyle and Kaye has the ability to help our co-developer, Mark. We are calling you, Kyle and Kaye to help us developing our code for this project. Kyle and Kaye, could you help Mark, and us co-developers on creating code for our current project and become one of us as another co-developers? Thank you.

**Comment by Kyle-Marie-Baita** [comment]
> In developing a tkinter code, our co-developer, Mark, need more help from another co-developers with specialty on this specific tkinter subject, and fortunately, both of you Kyle and Kaye has the ability to help our co-developer, Mark. We are calling you, Kyle and Kaye to help us developing our code for this project. Kyle and Kaye, could you help Mark, and us co-developers on creating code for our current project and become one of us as another co-developers? Thank you.

I agree. I will definitely help you guys.

**Comment by Mervz22** [comment]
Thank you for your feedbacks.
