### ISSUE TITLE
Encode tkinter features

### ISSUE THREAD

**Issue by Mervz22** [CkayeValencia/Et0eh-L4ng-Ak03h#3]
Good evening, we are now going to start for GUI coding. Could you guys upload a clean python file so that we could put codes inside of it? on developer branch. And brain storm for the GUI features and create a code for it. Once you are done with the code, please input it to the clean file that you have uploaded. Thank you.

**Comment by Mervz22** [comment]
I suggest to use tkinter since it is quite east, but feel free to use whatever you guys think is easier

**Comment by LapasaranMarkClarence** [comment]
Ok, I also prefer tkinter.

**Comment by Kyle-Marie-Baita** [comment]
I agree

**Comment by CkayeValencia** [comment]
no problem, but could you assign us what part in the code we could work on?

**Comment by Kyle-Marie-Baita** [comment]
> no problem, but could you assign us what part in the code we could work on?

yeah that's right. I think we should assign each of us a work to do so we can create the code way more faster.

**Comment by LapasaranMarkClarence** [comment]
> > no problem, but could you assign us what part in the code we could work on?
> 
> yeah that's right. I think we should assign each of us a work to do so we can create the code way more faster.
Sige, mas mainam ng ganyan.

**Comment by LapasaranMarkClarence** [comment]
Ba't kayo nag Eenglish? pwede naman tagalog! 🤣🤣

**Comment by Mervz22** [comment]
Alright, mas maisasuggest ko na mag meet nalang kayo virtually, like sa Gmeet o kahit anong app na nag aallow to meet with people, virtually.

**Comment by Kyle-Marie-Baita** [comment]
ou nga pwede tayo mag meet para mas madali

**Comment by CkayeValencia** [comment]
> Alright, mas maisasuggest ko na mag meet nalang kayo virtually, like sa Gmeet o kahit anong app na nag aallow to meet with people, virtually.

Pwede. Mag send ako link

**Comment by CkayeValencia** [comment]
Pwede kayo pumasok dito. https://meet.google.com/ycw-eefr-ths

**Comment by LapasaranMarkClarence** [comment]
As agreed in the meeting, 
kaye would do the loading screen and kyle would do the buttons and the label in the loading screen and the boys will focus on the coding for functions of the stopwatch.

**Comment by Kyle-Marie-Baita** [comment]
Okay po. Thank you for cooperating guys!!!

**Comment by KennethJonesDSerrano** [comment]
copy, I already  doing the codes for my part

**Comment by CkayeValencia** [comment]
Thank youuuuuuuu berybery much for cooperating guys!!
