### ISSUE TITLE
GUI Background and Icon/logo image

### ISSUE THREAD

**Issue by LapasaranMarkClarence** [CkayeValencia/Et0eh-L4ng-Ak03h#4]
Good morning Kaye and Kyle, request sana ako na  pasend ng image for our background and logo/icon

**Comment by Kyle-Marie-Baita** [comment]
good morning. May na post napo kami sa design branch. Pero if need tagala lahat ng files mas mabuti siguro if gagawa nalang atyo ng gdrive at doon natin isasave lahat.

**Comment by CkayeValencia** [comment]
Hello, ako nalang siguro mag send link sa gdrive? tas iupload mo nalang dun yung mga nagawa mo na kyle

**Comment by CkayeValencia** [comment]
https://drive.google.com/drive/folders/1mq_T0fjliYdqmOVaXPRM9rLeqvVEZMIf?usp=sharing

**Comment by Kyle-Marie-Baita** [comment]
I post na po sa gdrive paki check nalang po. Thank you

**Comment by LapasaranMarkClarence** [comment]
Thank you!
