### ISSUE TITLE
Tkinter codes posting

### ISSUE THREAD

**Issue by Mervz22** [CkayeValencia/Et0eh-L4ng-Ak03h#5]
Could you guys upload an empty python file and post all of y'all created codes inside of it on DEV branch?  We gotta need it tomorrow morning. Feel free to do and post it, anytime. Thank you!

**Comment by Kyle-Marie-Baita** [comment]
ok po

**Comment by CkayeValencia** [comment]
> Could you guys upload an empty python file and post all of y'all created codes inside of it on DEV branch? We gotta need it tomorrow morning. Feel free to do and post it, anytime. Thank you!

Done. Sorry for the delay btw

**Comment by LapasaranMarkClarence** [comment]
Na post ko na ang code ko. Sabihin niyo lang kung may mali or idagdag pa.

**Comment by LapasaranMarkClarence** [comment]
@Kyle-Marie-Baita Tapos na kami ni @CkayeValencia  sa pag post. Ikaw na next mag post ng code mo para maka proceed na sila @Mervz22 at @KennethJonesDSerrano .

**Comment by Kyle-Marie-Baita** [comment]
tapos na po. Na post ko na code ko

**Comment by Mervz22** [comment]
Thenks
