### ISSUE TITLE
Requesting for stopwatch codes 

### ISSUE THREAD

**Issue by KennethJonesDSerrano** [CkayeValencia/Et0eh-L4ng-Ak03h#6]
@Mervz22 please input the stopwatch code that you created if you are  already finish

**Comment by Mervz22** [comment]
I just finished the code, and will be send it in any minutes

**Comment by Mervz22** [comment]
I alreqdy posted it to the stopclock.py code.
![Screenshot_20220530_004949](https://user-images.githubusercontent.com/105393173/170881883-09c2edcf-6c6b-40bc-a5c0-344ec25d9031.jpg)
