### ISSUE TITLE
Buttons for stopwatch

### ISSUE THREAD

**Issue by Mervz22** [CkayeValencia/Et0eh-L4ng-Ak03h#7]
Hello, @KennethJonesDSerrano:
     If you have also finish your button codes, please post it to stopclock.py, and begin incoding it on line 143, thank you

**Comment by KennethJonesDSerrano** [comment]
Good morning, @Mervz22 natapos kuna lagay ang codes ko for buttons but I started editing in line 99 in able to apply the switching buttons.
