### ISSUE TITLE
There's something wrong in our code

### ISSUE THREAD

**Issue by Kyle-Marie-Baita** [CkayeValencia/Et0eh-L4ng-Ak03h#8]
Delay po ang time at mali po yung button na lumalabas

**Comment by Kyle-Marie-Baita** [comment]
Kindly help po

**Comment by KennethJonesDSerrano** [comment]
Okay @Kyle-Marie-Baita  thankyou for informing us. I will check it and fix the problem for buttons.

**Comment by Mervz22** [comment]
stop watch fixed.

**Comment by KennethJonesDSerrano** [comment]
Na ayos kuna ang buttons @Kyle-Marie-Baita.
