### ISSUE TITLE
About our Video

### ISSUE THREAD

**Issue by Kyle-Marie-Baita** [CkayeValencia/Et0eh-L4ng-Ak03h#9]
kindly plss list all the features we have so that we can assign each members what they need to present in the video.

**Comment by Kyle-Marie-Baita** [comment]
much better siguro guys if tayo lahat makita sa video

**Comment by CkayeValencia** [comment]
Ok. but who will edit? if no one, can I volunteer?

**Comment by Mervz22** [comment]
Stop watch features


- 2 GUI, 1 from intro and 2nd is the timer itself
- With cool bacground and icon
- Buttons are quite dynamic
- Exact timer and other feature as what phone timer has like laps etc.
- heart cursor
- Background music for better use

**Comment by Kyle-Marie-Baita** [comment]
So gihati hati ko na guys @CkayeValencia ikaw po intro at sa first interface. Ako na sa logo and background. @KennethJonesDSerrano ikaw nalang po sa button features. @LapasaranMarkClarence ikaw nalang po sa minimize and exit features. and @Mervz22 ikaw nalang po sa lap, music and cursor features

**Comment by CkayeValencia** [comment]
> So gihati hati ko na guys @CkayeValencia ikaw po intro at sa first interface. Ako na sa logo and background. @KennethJonesDSerrano ikaw nalang po sa button features. @LapasaranMarkClarence ikaw nalang po sa minimize and exit features. and @Mervz22 ikaw nalang po sa lap, music and cursor features

Okieee. Tomorrow nalang ako magtanggap ng mga vids, and dun lang isend ang vid sa gdrive natin https://drive.google.com/drive/folders/1mq_T0fjliYdqmOVaXPRM9rLeqvVEZMIf?usp=sharing

**Comment by LapasaranMarkClarence** [comment]
Ok po. Gagawa po ako mamaya ng video.

**Comment by KennethJonesDSerrano** [comment]
okay, asikasuhin ko na ang video.

**Comment by Mervz22** [comment]
> 

Okidokiiiii

**Comment by CkayeValencia** [comment]
Hi guys!, Update lang, Ive done editing the video if you want to see go to this link  https://drive.google.com/file/d/181UdP2nLA3M5gbihnB1s4xgj6qtsVnMt/view?usp=sharing

**Comment by Kyle-Marie-Baita** [comment]
Nakita ko na po. Nice

**Comment by KennethJonesDSerrano** [comment]
nice @CkayeValencia
